# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml
require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'lib/rubocop/ast/node_pattern/parser.racc.rb'
    - 'lib/rubocop/ast/node_pattern/lexer.rex.rb'
    - 'spec/rubocop/ast/node_pattern/parse_helper.rb'
    - 'spec/rubocop/ast/fixtures/*'
  TargetRubyVersion: 2.6
  SuggestExtensions: false

InternalAffairs/NodeMatcherDirective:
  Exclude:
    - 'spec/rubocop/ast/node_pattern_spec.rb'

Naming/PredicateName:
  # Method define macros for dynamically generated method.
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search

Style/FormatStringToken:
  # Because we parse a lot of source codes from strings. Percent arrays
  # look like unannotated format string tokens to this cop.
  Exclude:
    - spec/**/*

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - instance_methods
      - protected_methods
      - private_methods

# Trailing white space is meaningful in code examples
Layout/TrailingWhitespace:
  AllowInHeredoc: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Layout/HashAlignment:
  EnforcedHashRocketStyle:
    - key
    - table
  EnforcedColonStyle:
    - key
    - table

Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Lint/BooleanSymbol:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/PredicateMatcher:
  Strict: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/NestedGroups:
  Max: 7

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/FactoryBot/CreateList:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false
