name: Spell Checking

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  codespell:
    name: Check spelling of all files with codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: codespell-project/actions-codespell@v2
