name: Spell Checking

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  codespell:
    name: Check spelling of all files with codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: true
          ignore_words_file: codespell.txt
  misspell:
    name: Check spelling of all files in commit with misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install
        run: wget -O - -q https://raw.githubusercontent.com/client9/misspell/master/install-misspell.sh | sh -s -- -b .
      - name: Misspell
        run: git ls-files --empty-directory | xargs ./misspell -error
